model:                    # architecture details
    type: resnet50        # model name
    kwargs:
        num_classes: 1000
    path:  PATH_TO/checkpoints/resnet50_imagenet.pth.tar
data:
    path: PATH_TO/imagenet
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
sparse:
    cali_batchsize: 16
    reconstruction:
        pattern: block
        max_count: 20000
        keep_gpu: True
        weight_lr: 0.00001
    mask_generator:
      type: NormalMaskGenerator
      kwargs:
        sparsity: 0.6
    fake_sparse:
      type: FakeSparse
    scheduler:
      type: BaseScheduler
